# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d69abf82206ef964fa520205947fcb7c876102745d940d911cc43808a72736b77df7e65f841e05e4d4d04222a8fea581bd00af9b5c0b5bbbd811a1545120afa3

test:
  secret_key_base: c1e91826259cfb91daa8449a7d01b754031cbd52656fd787a7f6e1b4bc281eb40270901734d3ddfca223a8dc07c63e7ad108f54daf32adfb4fb46d251eefbb66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
